<a href="https://colab.research.google.com/github/pthangaraj-stack/Lab_exercise1/blob/main/PS_Numpy_Exercise_Batch8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

In [2]:
import numpy as np

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [3]:
#Solution

np.arange(10,30)

np.random.randint(10, 30, 30)

array([21, 20, 21, 28, 24, 22, 16, 14, 28, 11, 10, 25, 11, 27, 24, 28, 19,
       10, 14, 14, 22, 20, 25, 23, 27, 19, 26, 18, 29, 16])

#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [4]:
# Solution


arr1=np.arange(1, 51, 2)
print(arr1)
print('Length:', len(arr1))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
Length: 25


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [5]:
# Solution


np.linspace(4,7,27)

array([4.        , 4.11538462, 4.23076923, 4.34615385, 4.46153846,
       4.57692308, 4.69230769, 4.80769231, 4.92307692, 5.03846154,
       5.15384615, 5.26923077, 5.38461538, 5.5       , 5.61538462,
       5.73076923, 5.84615385, 5.96153846, 6.07692308, 6.19230769,
       6.30769231, 6.42307692, 6.53846154, 6.65384615, 6.76923077,
       6.88461538, 7.        ])

#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [6]:
# Solution
arr = np.random.randint(10, size=(5,4))

print(arr)

[[2 9 1 8]
 [9 2 4 0]
 [9 8 5 6]
 [1 4 5 7]
 [7 7 3 1]]


#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [7]:
# Solution

arr = np.random.randint(5, 16, size=(5,5))

print(arr)


[[11  8  7  8  6]
 [14 10  6 11  5]
 [10  5 14  7  9]
 [ 9  7 10 15 11]
 [ 5 14  7 11  7]]


#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [8]:
# Solution

arr1 = np.zeros((20-1,), dtype=int)

print(arr1)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [9]:
# Solution


np.ones((2, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [10]:
# Solution


arr= np.array([[9, 25, 50, 34, 45], [3, 34, 34, 65, 2], [5, 7, 3, 76, 3], [7, 8, 6, 54, 6], [23, 12, 8, 5, 8]])
print(arr)


[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [11]:
# Solution




#### 10. Print the all the elements of 3rd row of the matrix

In [12]:
# Solution

arr[2, 0:5]


array([ 5,  7,  3, 76,  3])

#### 11. Print the all the elements of 4th columns of the matrix

In [13]:
# Solution

arr[0:5, 3]


array([34, 65, 76, 54,  5])

#### 12. Print the 4 corner pixels of the matrix

In [14]:
# Solution

print(arr)



[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [15]:
# Solution 

arr= np.array([[9, 25, 50, 34, 45], [3, 34, 34, 65, 2], [5, 7, 3, 76, 3], [7, 8, 6, 54, 6], [23, 12, 8, 5, 8]])


arr

m1=arr[0:2, 2:4]
print('array m1\n', m1)

print('\n')

m2=arr[3:6, 0:2]
print('array m2\n', m2)

print('\n')

m3=arr[2:6, 2:6]
print('array m3\n', m3)

array m1
 [[50 34]
 [34 65]]


array m2
 [[ 7  8]
 [23 12]]


array m3
 [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [16]:
# Solution

m1 = m1.reshape(1, 4)
print('array m1: ', m1)

print('\n')

m2 = m2.reshape(1, 4)
print('array m2: ', m2)

print('\n')

m3 = m3.reshape(1, 9)
print('array m3: ', m3)

array m1:  [[50 34 34 65]]


array m2:  [[ 7  8 23 12]]


array m3:  [[ 3 76  3  6 54  6  8  5  8]]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [17]:
# Solution


ar=np.concatenate((m1, m2), axis=0)
ar.T

array([[50,  7],
       [34,  8],
       [34, 23],
       [65, 12]])

#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [18]:
# Solution


print('array m1: ', m1)
print('\n')
print('array m2: ', m2)



array m1:  [[50 34 34 65]]


array m2:  [[ 7  8 23 12]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [19]:
arr= np.array([[9, 25, 50, 34, 45], [3, 34, 34, 65, 2], [5, 7, 3, 76, 3], [7, 8, 6, 54, 6], [23, 12, 8, 5, 8]])

In [20]:
m1=arr[0:2, 2:4]
print('array m1\n', m1)

array m1
 [[50 34]
 [34 65]]


In [21]:
m3=arr[2:6, 2:6]
print('array m3\n', m3)

array m3
 [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


In [22]:
# Solution

m1=arr[0:2, 2:4]
print('array m1\n', m1)

print('\n')

m3=arr[2:6, 2:6]

m3=m3[1:, :2]
print('array m3\n', m3)

print('\n')

# Perform addition
print('sum of 2 array: \n', m1+m3)

array m1
 [[50 34]
 [34 65]]


array m3
 [[ 6 54]
 [ 8  5]]


sum of 2 array: 
 [[56 88]
 [42 70]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [23]:
# Solution

m1=arr[0:2, 2:4]
print('array m1\n', m1)

print('\n')

me1 = m1.mean()
print('Mean of me1: ', me1)

print('\n')

m2=arr[3:6, 0:2]
print('array m2\n', m2)

print('\n')

me2 = m2.mean()
print('Mean of me2: ', me2)

print('\n')

me = np.array([me1, me2])
print('me: \n', me)

print('\n')

m4 = np.array([[me1, me2]])
m4 = np.concatenate((m1, m4), axis=0)
m4

array m1
 [[50 34]
 [34 65]]


Mean of me1:  45.75


array m2
 [[ 7  8]
 [23 12]]


Mean of me2:  12.5


me: 
 [45.75 12.5 ]




array([[50.  , 34.  ],
       [34.  , 65.  ],
       [45.75, 12.5 ]])

#### 19. Perform the matrix multiplication between m3 and m4

In [24]:
# Solution

print('array m3\n', m3)

print('array m4\n', m4)

result = np.dot(m4, m3)
print('\n')

print('Matrix multiplication Result: \n', result)

array m3
 [[ 6 54]
 [ 8  5]]
array m4
 [[50.   34.  ]
 [34.   65.  ]
 [45.75 12.5 ]]


Matrix multiplication Result: 
 [[ 572.  2870. ]
 [ 724.  2161. ]
 [ 374.5 2533. ]]


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [25]:
arr= np.array([[9, 25, 50, 34, 45], [3, 34, 34, 65, 2], [5, 7, 3, 76, 3], [7, 8, 6, 54, 6], [23, 12, 8, 5, 8]])
print(arr)

[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]


In [26]:
# Solution
print('Mean (0): ', arr.mean(0))

print('Mean (1): ', arr.mean(1))

print('Variance: ', arr.var())

print('Variance: ', arr.var())

print('Standard Deviation: ', arr.std())

Mean (0):  [ 9.4 17.2 20.2 46.8 12.8]
Mean (1):  [32.6 27.6 18.8 16.2 11.2]
Variance:  456.44159999999994
Variance:  456.44159999999994
Standard Deviation:  21.364493909287905


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [27]:
runs_arr= np.array([[54, 60, 10, 65], [102, 2, 78, 32], [3, 110, 1, 92], [56, 6, 12, 42], [12, 8, 22, 11]])
runs_arr

array([[ 54,  60,  10,  65],
       [102,   2,  78,  32],
       [  3, 110,   1,  92],
       [ 56,   6,  12,  42],
       [ 12,   8,  22,  11]])

In [28]:
balls_arr= np.array([[50, 42, 22, 78], [95, 8, 65, 43], [9, 100, 7, 101], [27, 3, 11, 31], [24, 20, 36, 27]])
balls_arr

array([[ 50,  42,  22,  78],
       [ 95,   8,  65,  43],
       [  9, 100,   7, 101],
       [ 27,   3,  11,  31],
       [ 24,  20,  36,  27]])

In [29]:
# Solution 
total_runs_arr = runs_arr.sum(axis=1)
print('Total runs by players: ', total_runs_arr)
total_balls_arr = balls_arr.sum(axis=1)
print('Total balled faced by players: ', total_balls_arr)

strike_arr = (total_runs_arr/total_balls_arr)*100
print('strike rate of players: ', strike_arr)

array_copy = np.sort(strike_arr)[::-1]
print('Players decending-order based on strike rate: ', array_copy)

print('Players average: ', total_runs_arr.mean(axis=0))

Total runs by players:  [189 214 206 116  53]
Total balled faced by players:  [192 211 217  72 107]
strike rate of players:  [ 98.4375     101.42180095  94.93087558 161.11111111  49.53271028]
Players decending-order based on strike rate:  [161.11111111 101.42180095  98.4375      94.93087558  49.53271028]
Players average:  155.6


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [44]:
# Solution

marks = np.array([65,84,47,56,89,98,48,77,80,39])
marks

record = {
  'Marks': [65,84,47,56,89,98,48,77,80,39]}

dataframe = pd.DataFrame(record, columns = ['Marks'])

rslt_df = dataframe[dataframe['Marks'] > 50]

print('\n Result dataframe :\n', rslt_df)

print('\n Number of students passed:  :', rslt_df.count())
print('\nNumber of students failed:  :', dataframe.count()-rslt_df.count())


 Result dataframe :
    Marks
0     65
1     84
3     56
4     89
5     98
7     77
8     80

 Number of students passed:  : Marks    7
dtype: int64

Number of students failed:  : Marks    3
dtype: int64


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [18]:
# Solution

import numpy as np

marks = np.array([65,84,47,56,89,98,48,77,80,39])
print('student marks: ', marks)

marks_final=marks

marks1 = marks[(marks > 45) & (marks < 49)]
print('student marks 45-49: ', marks1)

marks2 = marks[marks > 80]
print('student marks > 80: ', marks2)

print('\nResults follows:')
marks1=marks1+5
print('student marks 45-49 with bonus: ', marks1)
marks2=marks2 + 5
print('student marks with bonus > 80: ', marks2)

marks2 = marks2 % 100
print('Modulas', marks2)

marks_final = np.where(((marks_final > 45) & (marks_final < 49) | (marks_final > 80)), marks_final+5, marks)
marks_final = np.where((marks_final > 100), 100, marks_final)
print('Final marks: ', marks_final)

print('Pass percentage: ', (marks_final.sum())/(10))

student marks:  [65 84 47 56 89 98 48 77 80 39]
student marks 45-49:  [47 48]
student marks > 80:  [84 89 98]

Results follows:
student marks 45-49 with bonus:  [52 53]
student marks with bonus > 80:  [ 89  94 103]
Modulas [89 94  3]
Final marks:  [ 65  89  52  56  94 100  53  77  80  39]
Pass percentage:  70.5


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [32]:
# Solution

# (x(i)^2 +8) / y(i)

import timeit

timeit.timeit()

#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [19]:
# Solution


https://github.com/pthangaraj-stack/Lab_exercise1


SyntaxError: ignored